server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: catalog
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog?readPreference=primary&appname=catalog_app&directConnection=true&ssl=false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka